server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

datasource:
  h2:
    dna:
      jdbcUrl: jdbc:h2:file:/tmp/Dna.db
      username: 'sa'
      password: ''
      driver-class-name: org.h2.Driver