server:
  port: 9090
  tomcat:
    max-threads: 400

spring:
  h2:
    console:
      enabled: true

datasource:
  h2:
    dna:
      jdbcUrl: jdbc:h2:mem:Dna
      username: 'sa'
      password: ''
      driver-class-name: org.h2.Driver